name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: bdayer
        path: ./bdayer

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bdayer
          path: .

      - name: Set file permissions
        run: chmod 0755 ./bdayer

      - name: Create a test roster
        run: |
          echo '# <day>,<month>,<anything>' > roster.txt
          echo '# Like that...' >> roster.txt
          echo '11,21,Name Surname' >> roster.txt
          echo '06,22,Me' >> roster.txt
          echo '07,14,Some day in the future' >> roster.txt
          echo '06,11,Billy' >> roster.txt
          echo >> roster.txt
          echo '03,14,Albert Einstein' >> roster.txt
          echo '03,01,Frédéric Chopin' >> roster.txt

      - name: See directory structure
        run: ls -l

      - name: Run bdayer
        run: BDAYER_ROSTER=$(pwd)/roster.txt ./bdayer
